### ISSUE TITLE
【bitflyer】ポジションが変化しない

### ISSUE THREAD

**Issue by Mousekozo** [penta2019/btc_bot_framework#1]
**問題**
simple_example_bot.pyを動作させたところ、ポジションを持っても表示が0のまま
'comission'が存在しないエラーが発生

**修正**
4箇所'comission'を'commission'に変更するとポジションを正しく取得するようになりました

https://github.com/penta2019/btc_bot_framework/blob/a90078b6ebf4b2e9fdf1c4ff346a90c7d2bec1b9/botfw/bitflyer/order.py#L138-L156

わかりやすいフレームを作成して下さり、ありがとうございます

**Comment by penta2019** [comment]
報告ありがとうございます。
おそらくこのコミットの際に約定時の動作まで確認していなかったのが原因です。
7467b1d5065d2106eeda985dd8d746f2d391ed6c
ご指摘の通り、綴ミスが４箇所あったのでこちらのコミットで修正しました。
1151da13bf9c5938195ecec99a6130d147209cca
