### ISSUE TITLE
ApiBaseのcapacity, countあたりがccxt 1.33.13以降のバージョンで動かなくなっている

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#11]
https://github.com/ccxt/ccxt/commit/654604c9d1d5e9d0f9d6a8937ed842d96154b759

この辺のコミットの影響だと思いますが、私にはこれ以上わかりませんでしたm(_ _)m

**Comment by penta2019** [comment]
確認しました。
おそらくmixinで上書きしていたrequest()が呼ばれなくなったのが原因だと思うので修正でき次第コミットします。

**Comment by penta2019** [comment]
473行目で
Exchange.define_rest_api(value, method_name, paths + [key])
のように基底クラスのExchangeを明示的に指定しているのが原因でした。
cls.define_rest_api(value, method_name, paths + [key])の様に書いてくれればこれまで通り問題なく動くのですが、仕方ないので今まで無駄な関数呼び出しだと思ってスキップしていたfetch2を上書きする形にしました。

**Comment by meetaco** [comment]
なるほど、勉強になります。ありがとうございました。
