### ISSUE TITLE
og.get_orders()を呼び出すと、RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#12]
●現象
botのコードの中でog.get_orders()を定期的に呼び出しているのですが、稀に以下のようなエラーが発生します。

> File "/usr/lib/python3.6/site-packages/botfw/base/order.py", line 489, in get_orders
> for o in self.manager.order_manager.orders.values():
> RuntimeError: dictionary changed size during iteration

●原因
おそらくループ中に別スレッドでself.manager.order_manager.ordersの注文情報が増減すると起こるのではないかと思っています。

●解決案
ループ用に一旦別オブジェクトを生成してやると実行時間は長くなりますが回避できます。
`for o in list(self.manager.order_manager.orders.values()):`

いかがでしょうか？

**Comment by penta2019** [comment]
すみません。通知に気づかず返信が遅くなってしまいました。
スレッド絡みのイテレーションエラーが低確率で発生する可能性があることは承知していたのですが、ほぼ発生しないだろうと思っていたので放置していました。
文面から察するに一度や二度では無さそうなので、解決案の通りに修正します。

**Comment by meetaco** [comment]
いえいえ、お時間ある時でいつでも大丈夫です。
そうですね、頻度は低いものの何度か発生しておりました。
助かりました。ありがとうございました。
