### ISSUE TITLE
bybitのprivate_get_position_listがccxt 1.40.50で動かない

### ISSUE THREAD

**Issue by EYLE-i** [penta2019/btc_bot_framework#13]
sample/simple_bot.pyをbybitでBTC/USDで動かしてみたところ、

>   File "/Users/usr/.local/lib/python3.8/site-packages/botfw/bybit/api.py", line 14, in __init__
    self.private_get_position_list = getattr(
AttributeError: 'BybitApi' object has no attribute 'private_get_position_list'

のエラーが発生しました。調べてみたところ、
https://github.com/ccxt/ccxt/issues/6827
のページがあり、ccxtの1.26.66?の以降のバージョンで変更があったみたいです。

botfw/bybit/api.py:14~15 の部分の
```
self.private_get_position_list = getattr(
            self, 'private_get_position_list')
```
を
```
self.privateLinearGetPositionList = getattr(
            self, 'privateLinearGetPositionList')
```
と修正したところ、simple_bot.pyがエラーなく動きました。

**Comment by penta2019** [comment]
2重でIssueが投稿されているようなので、こちらはクローズさせていただきますね。
詳細は#14の方をご覧ください。
