### ISSUE TITLE
bybitのprivate_get_position_listがccxt 1.40.50 で動かない

### ISSUE THREAD

**Issue by EYLE-i** [penta2019/btc_bot_framework#14]
sample/simple_bot.pyをbybitでBTC/USDで動かしてみたところ、

>   File "/Users/usr/.local/lib/python3.8/site-packages/botfw/bybit/api.py", line 14, in __init__
    self.private_get_position_list = getattr(
AttributeError: 'BybitApi' object has no attribute 'private_get_position_list'

のエラーが発生しました。調べてみたところ、
https://github.com/ccxt/ccxt/issues/6827
のページがあり、ccxtの1.26.66?の以降のバージョンで変更があったみたいです。

botfw/bybit/api.py:14~15 の部分の
```
self.private_get_position_list = getattr(
            self, 'private_get_position_list')
```
を
```
self.privateLinearGetPositionList = getattr(
            self, 'privateLinearGetPositionList')
```
と修正したところ、simple_bot.pyがエラーなく動きました。

**Comment by penta2019** [comment]
報告ありがとうございます！

調べたところによるとエラーの原因はccxtの最近の変更(1.40.44)が原因のようです。
https://github.com/ccxt/ccxt/commit/15adddddc508c579c21070d66c222d6fc1187784#diff-63d4b0e207cf8f71e0adf74f59caa0bf184cc2caa54e663f1edd63ac1f3b6a2a

private_get_position_listはv2_private_get_position_listに変更されたようです。
修正案にあったprivateLinearGetPositionListは自分の理解が正しければUSDT無期限（USDTを証拠金とする取引）のポジションを取得するAPIのようです。

現状、インバース無期限（Base通貨を証拠金とする取引）のみにしか対応していませんが、USDTを証拠金にしたほうが扱いやすいと思うので、近いうちにUSDT無期限にも対応するつもりです。

**Comment by EYLE-i** [comment]
そのバージョンでの変更だったのですね！
わざわざ調べていただきありがとうございます。
