### ISSUE TITLE
Realtime Private Channelの注文イベントのコールバック関数追加の機能について

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#3]
ぺんたさんはじめまして、フレームワーク早速活用させていただいております。

約定データと板情報のアップデートタイミングでのコールバック関数はadd_callback()で自由に設定できるようになっていると思うのですが、
同様に、bitflyerでいうとRealtime Private Channelの注文イベントの受信時に呼ばれるコールバック関数を自由に追加・削除できるような機能についてどう思われますでしょうか？
単純に、約定タイミングでログ出力や、外部DBへのinsertを行えると便利かなと思いました。

**Comment by penta2019** [comment]
ちょうど自分もそのような機能がほしいなと感じていたところでした。なるべく早く追加します。
現状、力技ではありますが、以下の方法で注文イベントを捕捉することができます。

```
fx_og = ogm.create_order_group(FX_BTC_JPY, 'fx')
handle_event = fx_og._handle_event  # 元々のハンドラを控える

def handle_event2(e):  #ハンドラを新しく定義
    handle_event(e)  # 元々のハンドラを呼び出す
    print(e.__dict__)  # 行いたい処理

fx_og._handle_event = handle_event2  # 新しく作ったハンドラに置き換える
```

**Comment by meetaco** [comment]
おお、ありがとうございます。楽しみにしてます。
力技の方も参考にさせていただきます。
