### ISSUE TITLE
EVENT_OPENの注文イベントのws受信の際、価格とサイズがOrderEventのインスタンスに格納されていない

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#4]
先日は機能実装ありがとうございました！

その機能について、タイトル通りなのですが、これはなにか意図があってのことでしょうか？
もしなければこちらでpull reqつくらせてください。

**Comment by penta2019** [comment]
OrderEventのpriceとsizeはEVENT_EXECUTION専用のフィールドです。
ポジションの計算や平均約定価格の計算等に使用します。
OPEN時の価格とサイズが必要な場合はidからom.orders[event.id]もしくはog.orders[event.id]のようにして注文オブジェクトを参照してください。

**Comment by meetaco** [comment]
なるほど、分かりました！
ありがとうございます。
