### ISSUE TITLE
ポジション自動修復機能のバグ

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#6]
`ogm.set_position_sync_config(SYMBOL, MIN_SIZE, MIN_SIZE * 100)`

として設定しても、
> [09:53:04.651 W BitflyerOrderGroupManager] detect position mismatch between server(0.02) and client(0.0).

のメッセージが出力されるのみで、実際に修復が行われませんでした。

該当メッセージ出力部分のコードを見ると、detectのメッセージ出力の部分と実際に修復する部分でif-else分岐が行われておりどちらかしか呼ばれていないように思います。

また、そのif-else文から数行上の
```
if server == client:
    self.position_diff = 0
    continue
```
この部分を下のif-else文に統合してしまえると思います。
（揚げ足取るようであれなのですがself.position_diffはconf.position_diffのミスかなとも思います）

見当違いのこと言ってたらすみません！
よろしくお願いしますm(_ _)m

**Comment by penta2019** [comment]
報告ありがとうございます。
これは自分の説明不足でもあるのですが、ポジションずれを警告するのみで実際には修復が行われないことがあるのは仕様です。
極稀にポジションの取得タイミングの問題で実際にはポジションがズレていないにもかかわらず、ズレていると誤検知してしまう場合があります。
なのでズレを検知してもすぐには修正を行わずに、次のチェック時（デフォルトでは60秒間隔）に再度チェックを行い、ズレが一致した場合にのみ修正を行います。
self.position_diffの方はバグのようなので修正しておきます。

**Comment by meetaco** [comment]
なるほど、そこまで読み取れていませんでした。
ご回答ありがとうございます。
