### ISSUE TITLE
BitMEXのcommissionのPositionGroupでの管理について

### ISSUE THREAD

**Issue by meetaco** [penta2019/btc_bot_framework#7]
BitMEXのcommission情報は約定した際にレート(0.025%のマイナス手数料なら-0.00025)で渡されるので、PositionGroupでcommissionとpnlを管理する際に絶対額に変換してやる必要があるように思います。

bitflyerの場合は絶対額で渡されるので現状で問題ないです。
binance futuresの場合は未確認です。

**Comment by meetaco** [comment]
BitMEXのcomission情報は約定した際にレート(0.025%のマイナス手数料なら-0.00025)で渡されるので、PositionGroupでcomissionとpnlを管理する際に絶対額に変換してやる必要があるように思います。

bitflyerの場合は絶対額で渡されるので現状で問題ないです。
binance futuresの場合は未確認です。

**Comment by penta2019** [comment]
そういう仕様だったんですね！絶対額だと思ってました。
すぐに修正します。

**Comment by penta2019** [comment]
binanceのcommissionは絶対額のようなので現在の実装で大丈夫みたいです。
いつもありがとうございます！

**Comment by meetaco** [comment]
ありがとうございました！
このフレームワーク導入してからbotのコードがすっきりして実装もメンテもかなり楽になりました。
しばらくお世話になると思うのでよろしくお願いします🐙

**Comment by meetaco** [comment]
commission絶対額計算の際にrateにsizeをかけるように変更してもらったと思うのですが、そのsizeが買いのときと売りのときで正負2通り来るので、commissionの絶対額が、買いか売りかによって正になったり負になったりしてしまいます。
commissionの正負は買いか売りかではなくtakeかmakeかによって決まりますので、現状だと問題かと思われます。
sizeの絶対値をとったほうが良さそうです。

**Comment by penta2019** [comment]
報告ありがとうございます。自分で決めた仕様なのに失念していました。
この仕様については時々,sideとsizeに分けたほうがいいのかもしれないと思うことがあります。

**Comment by meetaco** [comment]
僕はsizeに正負の情報も入れてしまう方が好きですよ。
ただ大体はsideとsizeに分かれてるのでそれと揃えるという意味では難しいところですよね。

あとちょっと別の話にはなるんですが、sizeはsideと見た目が似てて混同してしまうと困るので、個人的にはsizeの代わりにamountを使うようにしてます。

**Comment by penta2019** [comment]
executionだけ売買が符号なのがちょっと気になってましたが、そういうことならそのままで行こうと思います。
amountといえばccxtと変数名を揃えるために注文周りだけsizeを避けていて、amount(正の値)、size(符号付き、主にexecution用)で使い分けていたのを思い出しました。
